# Generated by Django 6.0.1 on 2026-02-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_authors',
            field=models.ManyToManyField(through='blog.Comment', to='blog.author'),
        ),
    ]
