# Generated by Django 6.0.1 on 2026-02-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_views_alter_tag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_authors',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='blog.tag'),
        ),
    ]
